doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/migrations'
    organize_migrations: BY_YEAR_AND_MONTH
    storage:
        table_storage:
            table_name: 'migrations'
            version_column_name: 'version'
            version_column_length: 192
            executed_at_column_name: 'executed_at'
    check_database_platform: false

